import React, { useEffect, useRef, useState } from 'react';
import { createRoot, hydrateRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowRight, ChevronRight, Menu, X, Plus, Minus, Phone, Mail, Camera, ScanSearch, ClipboardCheck, ClipboardList, FileText, Container, Ship, Truck, Factory, Anchor, Handshake, ShieldCheck, Eye, Receipt, MapPin, FileBadge, Stamp, Route, Earth, BadgeCheck, Building2, Linkedin, Facebook, Instagram, Award, Landmark, Globe, Users, Target } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import ShipScene from './components/ShipScene';
import { nav, grades, pulpDescriptions, photos, serviceItems, credentials, profiles, industries, type Photo } from './data';
import './style.css';
import './sections.css';
import './updates.css';


gsap.registerPlugin(ScrollTrigger);
const email = 'veenexusglobal@gmail.com';
const mailto = `mailto:${email}?subject=${encodeURIComponent('Enquiry from website')}`;
const whatsapp = 'https://wa.me/919884140368?text=' + encodeURIComponent('Hello Vee Nexus, I would like to discuss recovered paper / pulp.');
const paperPhoto:Photo = {src:'/paper.webp', small:'/paper-small.webp', alt:'Close-up of layered recovered corrugated paper'};
const portPhoto:Photo = {src:'/port.webp', small:'/port-mobile.webp', alt:'Shipping containers in an international port'};
const steps = [
  {name:'Recovered paper', verb:'Source', text:'A new journey starts with recovered material from reliable international suppliers.', photo:photos.occBales},
  {name:'Quality verification', verb:'Verify', text:'Specifications, moisture, outthrows and material evidence are reviewed against the mill’s needs.', photo:photos.baleInspect},
  {name:'Global sourcing', verb:'Connect', text:'We match available supply with genuine Indian paper-mill requirements.', photo:portPhoto},
  {name:'Ocean freight', verb:'Coordinate', text:'Commercial discussions and shipment coordination connect origin with destination.', photo:photos.containerShip},
  {name:'Indian paper mills', verb:'Transform', text:'Recovered fibre becomes a resource for the next production cycle.', photo:photos.boardMill},
  {name:'New paper products', verb:'Renew', text:'Material returns to use through sustainable paper production.', photo:paperPhoto},
];
const origins = [
  {name:'USA', x:225,y:145, flag:'us'}, {name:'Canada',x:217,y:90, flag:'ca'}, {name:'UK',x:493,y:98, flag:'gb'},
  {name:'Europe',x:535,y:110, flag:'eu'}, {name:'Central America',x:256,y:209, flag:''}, {name:'Middle East',x:630,y:173, flag:''},
  {name:'New Zealand',x:983,y:364, flag:'nz'},
];
function Picture({photo,sizes='(max-width:640px) 88vw, 48vw'}:{photo:Photo;sizes?:string}){return <img src={photo.src} srcSet={`${photo.small} 800w, ${photo.src} 1400w`} sizes={sizes} alt={photo.alt} loading="lazy"/>}
function Brand(){return <a className="brand" href="#home"><strong>VEE NEXUS</strong><span>GLOBAL RESOURCE</span></a>}
function Action({href,children,outline=false}:{href:string;children:React.ReactNode;outline?:boolean}){return <a className={`action ${outline?'action-outline':''}`} href={href}><span>{children}</span><ArrowUpRight size={18}/></a>}
function Navigation(){
  const [menu,setMenu]=useState(false);const [active,setActive]=useState('home');const [solid,setSolid]=useState(false);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActive(e.target.id)},{rootMargin:'-20% 0px -55% 0px'});nav.forEach(([,id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});const hero=new IntersectionObserver(([e])=>setSolid(!e.isIntersecting),{rootMargin:'-80px 0px 0px 0px'});const el=document.getElementById('hero-top');if(el)hero.observe(el);return()=>{observer.disconnect();hero.disconnect()}},[]);
  useEffect(()=>{if(!menu)return;const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);document.getElementById('menu-toggle')?.focus()}};document.addEventListener('keydown',listener);return()=>document.removeEventListener('keydown',listener)},[menu]);
  return <header className={`site-header ${solid||menu?'is-solid':''}`}><Brand/><nav className={menu?'navigation open':'navigation'} id="mobile-nav" aria-label="Main navigation">{nav.map(([name,id])=><a key={id} href={'#'+id} aria-current={active===id?'location':undefined} onClick={()=>setMenu(false)}>{name}</a>)}</nav><a className="supplier-link" href="#supplier">Become a Supplier<ArrowUpRight size={17}/></a><button id="menu-toggle" className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
}
function About(){return <section className="about content" id="about"><div className="about-title"><p className="section-label">Vee Nexus Global Resource</p><h2>Global perspective.<br/>Grounded in Chennai.</h2></div><div className="about-body"><p>We connect international suppliers of recovered paper and pulp with Indian paper mills.</p><p>As a Chennai-based trading and indenting company, we focus on suitable material, genuine mill requirements and commercial terms that work for both sides.</p><div className="about-points"><span>Supplier verification</span><span>Quality-based procurement</span><span>Competitive commercial terms</span><span>Long-term partnerships</span></div></div><div className="about-photo"><img src="/port.webp" srcSet="/port-mobile.webp 800w, /port.webp 1600w" sizes="(max-width:640px) 88vw, 48vw" alt="Aerial view of containers arranged at a shipping port" loading="lazy"/><p>International supply. Indian market knowledge.</p></div><div className="about-statement">Recycle today.<br/>Better tomorrow.</div></section>}
function Gallery(){const items=[{photo:photos.occBales,label:'OCC bales',wide:true},{photo:photos.onpBundles,label:'ONP bundles'},{photo:photos.crane,label:'Container loading'},{photo:photos.truck,label:'Truck transportation'},{photo:photos.boardMill,label:'Paper mill',wide:true}];
 return <section className="gallery" aria-label="Material and shipping photographs"><div className="gallery-track" tabIndex={0} role="group" aria-label="Photographs, scroll sideways on small screens">{items.map(item=><figure key={item.label} className={item.wide?'wide':''}><Picture photo={item.photo} sizes="(max-width:640px) 80vw, 40vw"/><figcaption>{item.label}</figcaption></figure>)}</div><p className="gallery-note content">Recovered paper, from the baling yard to the paper mill. Photographs illustrate material categories.</p></section>}
function WhatsAppButton(){return <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Chat with Vee Nexus on WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M17.47 14.38c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.16-.17.2-.35.22-.64.08-.3-.15-1.26-.46-2.39-1.48-.88-.79-1.48-1.76-1.65-2.06-.17-.3-.02-.46.13-.6.13-.14.3-.35.45-.52.15-.18.2-.3.3-.5.1-.2.05-.37-.03-.52-.07-.15-.67-1.61-.91-2.2-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.48 0 1.46 1.07 2.88 1.21 3.07.15.2 2.1 3.2 5.08 4.49.71.3 1.26.49 1.7.63.71.22 1.36.19 1.87.12.57-.09 1.76-.72 2-1.41.25-.7.25-1.29.18-1.41-.08-.13-.28-.2-.57-.35m-5.42 7.4h-.01a9.87 9.87 0 0 1-5.03-1.38l-.36-.21-3.74.98 1-3.65-.24-.37a9.86 9.86 0 0 1-1.51-5.26c0-5.45 4.44-9.88 9.89-9.88 2.64 0 5.12 1.03 6.99 2.9a9.83 9.83 0 0 1 2.89 6.99c0 5.45-4.44 9.88-9.88 9.88m8.41-18.3A11.82 11.82 0 0 0 12.05 0C5.5 0 .16 5.34.16 11.89c0 2.1.55 4.14 1.59 5.95L.06 24l6.3-1.65a11.88 11.88 0 0 0 5.68 1.45h.01c6.55 0 11.89-5.34 11.89-11.9a11.82 11.82 0 0 0-3.48-8.4Z"/></svg><span className="whatsapp-label">Chat on WhatsApp</span></a>}
function Journey(){const [stage,setStage]=useState(0);const section=useRef<HTMLElement>(null);
  useEffect(()=>{const media=gsap.matchMedia();media.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{const trigger=ScrollTrigger.create({trigger:section.current,start:'top top',end:'bottom bottom',onUpdate:s=>setStage(Math.min(5,Math.floor(s.progress*6)))});return()=>trigger.kill()});return()=>media.revert()},[]);
  return <section className="journey" ref={section} id="journey"><div className="journey-sticky"><div className="journey-copy"><p className="section-label">The material journey</p><h2>Waste is only<br/>the beginning.</h2><div className="journey-description" key={stage}><span className="stage-number">0{stage+1}</span><div><h3>{steps[stage].name}</h3><p>{steps[stage].text}</p></div></div></div><div className={'journey-art stage-'+stage}><Picture key={steps[stage].photo.src} photo={steps[stage].photo}/><span className="journey-verb" aria-hidden="true">{steps[stage].verb}</span><div className="paper-window"/></div><div className="journey-controls" aria-label="Explore the material journey">{steps.map((step,i)=><button key={step.name} className={stage===i?'active':''} onClick={()=>setStage(i)} aria-pressed={stage===i}><span>0{i+1}</span>{step.name}<ChevronRight size={16}/></button>)}</div></div></section>}
const supplierGroups=[{title:'Company',items:['Company information','Monthly supply capacity','Loading port']},{title:'Product',items:['Product grade & origin','Quality specification','Moisture %, outthrows % and contamination details','Bale weight & dimensions',"40′ HC loading quantity"]},{title:'Commercial',items:['MOQ','Shipment lead time','FOB / CFR / CIF pricing','Payment terms']},{title:'Quality evidence',items:['Bale photographs','Loading photographs','Material videos','Inspection reports, if available']}];
function Supplier(){const [open,setOpen]=useState<number[]>([0]);const toggle=(i:number)=>setOpen(a=>a.includes(i)?a.filter(x=>x!==i):[...a,i]);return <section className="supplier content" id="supplier"><div className="supplier-heading"><p className="section-label">Become a Supplier</p><h2>Supply recovered paper?<br/>Let's talk.</h2><p>We welcome reliable international suppliers who can provide consistent quality and regular quantities.</p><Action href={`mailto:${email}?subject=Supplier%20introduction&body=Company%20name%3A%0AProduct%20grade%20and%20origin%3A%0AQuality%20specifications%3A%0AMonthly%20capacity%3A%0ALoading%20port%3A%0APricing%20and%20payment%20terms%3A%0A%0APlease%20attach%20material%20photographs%20and%20available%20inspection%20reports.`}>Send Supplier Details</Action></div><div className="supplier-checklist"><p>For a useful first conversation, please share:</p>{supplierGroups.map((group,i)=><div className="supplier-group" key={group.title}><button aria-expanded={open.includes(i)} aria-controls={'supplier-panel-'+i} onClick={()=>toggle(i)}>{group.title}{open.includes(i)?<Minus size={19}/>:<Plus size={19}/>}</button><div id={'supplier-panel-'+i} hidden={!open.includes(i)}><ul>{group.items.map(item=><li key={item}>{item}</li>)}</ul></div></div>)}</div></section>}
const profileIcon = {Facebook:Facebook, Instagram:Instagram, LinkedIn:Linkedin, IndiaMART:Globe, Alibaba:Globe};
function SocialLinks({className=''}:{className?:string}){
  const live=profiles.filter(p=>p.url);
  if(!live.length)return null;
  return <ul className={'social-links '+className} aria-label="Vee Nexus on business and social platforms">{live.map(p=>{const Icon=profileIcon[p.name];return <li key={p.name}><a href={p.url} target="_blank" rel="noopener noreferrer" aria-label={p.name} title={p.name}><Icon size={17}/><span>{p.name}</span></a></li>})}</ul>;
}
function Hero(){return <section className="hero" id="home"><div id="hero-top"/><div className="hero-heading"><p className="hero-intro"><img src="/flags/in.svg" alt="" width="20" height="15"/>Vee Nexus Global Resource · Chennai, India</p><h1><span>Global Sourcing.</span><span>Verified Quality.</span><span>Transparent Trade.</span></h1></div><ShipScene/><div className="hero-bottom"><div><h2>Connecting International Waste Paper Suppliers with Indian Paper Mills.</h2><p>Recycle Today, Better Tomorrow.</p></div><div className="hero-actions"><Action href="#products">Explore Our Products</Action><a className="simple-link" href={mailto}><Mail size={16}/>Email Us</a><SocialLinks className="hero-social"/></div></div><a className="hero-scroll" href="#about" aria-label="Explore the company"><ArrowDown size={21}/></a></section>}

const credentialIcon={registration:Landmark,'tie-up':BadgeCheck,platform:Globe};
function Credentials(){return <section className="credentials content" aria-labelledby="credentials-title"><div className="credentials-head"><p className="section-label">Business credentials</p><h2 id="credentials-title">Registered. Connected.<br/>Ready to trade.</h2><p>Our registrations, agency tie-ups and B2B platform presence.</p></div><div className="credential-grid">{credentials.map(c=>{const Icon=credentialIcon[c.kind];return <article className={'credential '+c.kind} key={c.name}><div className="credential-seal" aria-hidden="true"><Icon size={26}/></div><p className="credential-kind">{c.kind==='registration'?'Registration':c.kind==='tie-up'?'Agency tie-up':'B2B platform'}</p><h3>{c.name}</h3><p>{c.detail}</p>{c.id?<p className="credential-id">No. {c.id}</p>:c.kind==='registration'?<p className="credential-id">Certificate available on request</p>:null}{c.url&&<a className="simple-link" href={c.url} target="_blank" rel="noopener noreferrer">View profile<ArrowUpRight size={15}/></a>}</article>})}</div></section>}

function SampleReport({compact=false}:{compact?:boolean}){
  const rows=[['Commodity','OCC 11'],['Origin','—'],['Container no.','XXXX 000000-0'],['Bales inspected','—'],['Moisture','— %'],['Outthrows','— %'],['Prohibitives','— %']];
  return <figure className={'sample-report'+(compact?' compact':'')} aria-label="Example layout of a pre-shipment inspection report"><div className="report-head"><div><p>Pre-Shipment Product Inspection &amp; Verification</p><strong>Inspection Report</strong></div><span className="report-tag">Example</span></div><dl>{rows.slice(0,compact?4:rows.length).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="report-photos">{[photos.occBales,photos.baleInspect,photos.truck].map(p=><img key={p.src} src={p.small} alt="" loading="lazy"/>)}</div><div className="report-result"><ClipboardCheck size={18}/><span>Result: conforms to agreed specification</span></div><span className="report-stamp" aria-hidden="true">Inspected</span><figcaption>Example format only. Real reports come from the appointed inspection agency.</figcaption></figure>;
}
function CustomsVisual(){return <div className="customs-visual" aria-hidden="true">{[[Building2,'Authorised CHA'],[FileText,'Bill of entry'],[Landmark,'ICEGATE filing'],[Stamp,'Out of charge']].map(([Icon,label],i)=>{const I=Icon as typeof Stamp;return <div key={label as string}><I size={24}/><span>{label as string}</span>{i<3&&<ArrowRight size={15}/>}</div>})}</div>}
function Services(){return <section className="services content" id="services"><div className="services-title"><p className="section-label">Our services</p><h2>From inspection<br/>to the mill gate.</h2><p>Five services that move recovered paper safely from international suppliers to Indian paper mills.</p></div><div className="service-grid">{serviceItems.map(s=><article className={'service-card service-'+s.id} key={s.id}><div className="service-media">{s.photo?<Picture photo={s.photo} sizes="(max-width:640px) 88vw, 33vw"/>:s.id==='customs'?<CustomsVisual/>:<SampleReport compact/>}{s.flow&&<ol className="dispatch-flow" aria-label="Dispatch route"><li><Anchor size={16}/>Port</li><li><Truck size={16}/>Container truck</li><li><Factory size={16}/>Paper mill</li></ol>}</div><div className="service-body"><span className="service-letter">{s.letter}</span><h3>{s.title}</h3><p>{s.text}</p>{!s.flow&&<ul>{s.points.map(p=><li key={p}>{p}</li>)}</ul>}</div></article>)}</div><div className="services-cta"><p>Need one service or the complete chain?</p><Action href={`mailto:${email}?subject=${encodeURIComponent('Service enquiry')}`}>Enquire about our services</Action></div></section>}

function Industries(){return <section className="industries content" aria-labelledby="industries-title"><p className="section-label">Who we serve</p><h2 id="industries-title">Every mill needs<br/>a different fibre.</h2><div className="industry-grid">{industries.map((ind,i)=><article key={ind.name}><span>0{i+1}</span><h3>{ind.name}</h3><p>{ind.text}</p><ul aria-label={'Typical grades for '+ind.name}>{ind.grades.map(g=><li key={g}>{g}</li>)}</ul></article>)}</div></section>}

const specFields:[keyof typeof grades[number],string][]=[['origin','Origin'],['bale','Bale information'],['moisture','Moisture'],['outthrows','Outthrows'],['prohibited','Prohibited materials'],['quantity','Available quantity'],['inspection','Inspection option'],['terms','Shipment terms']];
function Products(){const [index,setIndex]=useState(0);const g=grades[index];
 return <section className="products content" id="products"><div className="products-title"><p className="section-label">Products</p><h2>Good material.<br/>The right match.</h2><p>Waste paper grades and manufacturing pulp, sourced to fit Indian mill requirements.</p></div><div className="materials"><div className="material-photo"><Picture key={g.photo.src} photo={g.photo}/><span className="material-type" aria-hidden="true">{g.name}</span></div><div className="material-browser"><div className="grade-buttons" role="group" aria-label="Select a product">{grades.map((grade,i)=><button key={grade.name} className={index===i?'selected':''} aria-pressed={index===i} onClick={()=>setIndex(i)}>{grade.name}{index===i?<ArrowUpRight size={18}/>:<Plus size={17}/>}</button>)}</div></div></div><article className="spec-sheet" aria-live="polite" key={g.name}><header><div><p>Product sheet</p><h3>{g.name}</h3><p className="spec-full">{g.full}</p></div><Action href={`mailto:${email}?subject=${encodeURIComponent('Product enquiry: '+g.name)}&body=${encodeURIComponent(`Product: ${g.name}\nRequired quantity:\nDestination port / mill:\nPreferred shipment terms:\n`)}`}>Enquire about {g.name}</Action></header><p className="spec-text">{g.text}</p><dl><div><dt>Grade</dt><dd>{g.name} · {g.full}</dd></div>{specFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{g[key] as string}</dd></div>)}</dl>{g.pulps&&<ul className="pulp-list" aria-label="Pulp types">{g.pulps.map(p=><li key={p}><strong>{p}</strong>{pulpDescriptions[p]}</li>)}</ul>}</article><p className="materials-note">Photographs illustrate each grade. Specifications are confirmed with the supplier and agreed with the buyer for every contract.</p></section>
}

const pin=(x:number,y:number)=>`M${x} ${y}c-5-8-9-12-9-17a9 9 0 1 1 18 0c0 5-4 9-9 17z`;
function Sourcing(){const [origin,setOrigin]=useState(0);const map=useRef<SVGSVGElement>(null);
 useEffect(()=>{const media=gsap.matchMedia();media.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{gsap.fromTo('.selected-route',{strokeDashoffset:1},{strokeDashoffset:0,duration:1.5,ease:'power2.inOut',scrollTrigger:{trigger:map.current,start:'top 85%',once:true}})},map);return()=>ctx.revert()});return()=>media.revert()},[origin]);
 const selected=origins[origin];
 return <section className="sourcing" id="sourcing"><div className="content sourcing-content"><div className="sourcing-title"><p className="section-label">Global sourcing</p><h2>Our Global<br/>Sourcing Network.</h2><ol className="network-flow" aria-label="Supply chain"><li>International Suppliers</li><li>Vee Nexus Global Resource</li><li>Indian Ports</li><li>Paper Mills</li></ol></div><div className="origins" role="group" aria-label="Explore sourcing regions">{origins.map((o,i)=><button key={o.name} onClick={()=>setOrigin(i)} aria-pressed={origin===i}>{o.flag?<img src={`/flags/${o.flag}.svg`} alt="" width="20" height="15"/>:<Earth size={16}/>}{o.name}</button>)}</div><div className="map-wrap"><img src="/world.svg" alt="World map" loading="lazy"/><svg ref={map} viewBox="0 0 1000 500" role="img" aria-label={`Sourcing regions: ${origins.map(o=>o.name).join(', ')}. Highlighted route from ${selected.name} to Chennai, India`}><g className="map-routes">{origins.map(o=><path key={o.name} d={`M${o.x},${o.y} Q${(o.x+722)/2},${Math.min(o.y,214)-110} 722,214`}/>)}</g><path className="selected-route" key={origin} pathLength="1" d={`M${selected.x},${selected.y} Q${(selected.x+722)/2},${Math.min(selected.y,214)-110} 722,214`}/>{origins.map((o,i)=><g key={o.name} className={'map-pin'+(i===origin?' active':'')} onClick={()=>setOrigin(i)}><path d={pin(o.x,o.y)}/><circle cx={o.x} cy={o.y-17} r="3.5"/></g>)}<g className="map-pin india"><path d={pin(722,214)}/><circle cx="722" cy="197" r="3.5"/></g><image href="/flags/in.svg" x="738" y="186" width="22" height="16.5"/><text x="766" y="199">Chennai, India</text><text className="origin-label" x={selected.x} y={selected.y+18} textAnchor={selected.x>900?'end':'middle'}>{selected.name}</text></svg></div><div className="sourcing-footer"><p>Quality. Availability. Pricing.<br/>Freight economics. Specifications. Reliability.</p><div><p>We welcome suppliers with consistent quality and regular monthly quantities.</p><small>Open to other suitable origins.</small></div></div></div></section>
}

const qaFlow:[typeof Camera,string][]=[[Camera,'Product photos'],[ScanSearch,'Inspection'],[FileBadge,'Inspection report'],[Container,'Container loading'],[Ship,'Shipment']];
function Quality(){return <section className="quality-verify content" id="quality"><div className="qa-copy"><p className="section-label">Inspection &amp; quality assurance</p><h2>Quality Verification<br/>Before Shipment.</h2><p>Product specifications and quality requirements are agreed between the relevant parties before shipment. Where required, third-party inspection can be arranged before container loading to verify the material against the agreed specifications.</p><ol className="qa-flow">{qaFlow.map(([Icon,label],i)=><li key={label}><span className="qa-icon"><Icon size={20}/></span><span className="qa-step">0{i+1}</span>{label}</li>)}</ol></div><SampleReport/></section>}

const processSteps=[['Buyer Requirement','Understand the paper mill’s required grade, specification and quantity.'],['Global Sourcing','Identify suitable suppliers and available material from international markets.'],['Product Verification','Review product specifications, bale photographs and quality requirements.'],['Commercial Discussion','Discuss price, quantity, shipment terms and payment conditions.'],['Pre-Shipment Inspection','Arrange third-party inspection according to the agreed product specifications, where required.'],['Container Loading & Shipment','Coordinate container loading and shipment documentation.'],['Consignment Tracking','Track the shipment and share relevant shipping and documentation updates.'],['Paper Mill Delivery','Coordinate port-to-paper-mill transportation and delivery.']];
function Process(){return <section className="process process-dark" id="process"><img className="process-bg" src={photos.paperMachine.src} srcSet={`${photos.paperMachine.small} 640w, ${photos.paperMachine.src} 1200w`} sizes="100vw" alt="" loading="lazy"/><div className="content"><p className="section-label">How we work</p><h2>A clear path<br/>from supplier to mill.</h2><div className="process-flow">{processSteps.map(([name,text],i)=><div className="process-step" key={name}><span>Step {i+1}</span><h3>{name}</h3><p>{text}</p>{i<processSteps.length-1&&<ArrowRight size={20}/>}</div>)}</div><p className="commercial-terms">Commercial discussions may include <strong>FOB</strong><strong>CFR</strong><strong>CIF Chennai</strong></p></div></section>}

const pillars:[typeof Award,string,string][]=[[Award,'Quality','We focus on sourcing products that meet the buyer’s agreed specifications and quality requirements.'],[Eye,'Transparency','Clear communication regarding product quality, quantity, pricing, documentation and shipment status.'],[ClipboardCheck,'Product Inspection','Where required, each transaction can include an agreed pre-shipment inspection and inspection report.'],[ShieldCheck,'Reliability','We aim to maintain consistent communication and coordination between suppliers and paper mills.'],[Handshake,'Long-Term Relationships','Our objective is to build sustainable business relationships with international suppliers and Indian paper mills.'],[Route,'Shipment Visibility','Relevant shipping documents and consignment tracking information are shared with the concerned parties.']];
function Partnership(){return <section className="partnership" id="partnership"><div className="content partnership-grid"><div className="partnership-photo"><Picture photo={photos.handshake}/></div><div><p className="section-label">Partnership</p><h2>Building Long-Term<br/>Business Partnerships.</h2><div className="pillars">{pillars.map(([Icon,title,text])=><article key={title}><Icon size={22}/><h3>{title}</h3><p>{text}</p></article>)}</div><div className="partnership-close"><p>Supply recovered paper or buy for a paper mill? Let’s start a conversation.</p><a href="#supplier" className="round-link" aria-label="Become a supplier"><ArrowUpRight size={30}/></a></div></div></div></section>}

function Values(){return <section className="values content" aria-label="Transparency and business relationship">{([[ShieldCheck,'Quality','Quality-focused sourcing based on agreed specifications.'],[Eye,'Transparency','Clear communication throughout the transaction and shipment process.'],[Users,'Relationship','Building professional, long-term relationships with suppliers and paper mills.']] as [typeof Eye,string,string][]).map(([Icon,title,text])=><article key={title}><span className="value-icon"><Icon size={30}/></span><h3>{title}</h3><p>{text}</p></article>)}</section>}

const documents:[typeof Receipt,string][]=[[Receipt,'Commercial Invoice'],[ClipboardList,'Packing List'],[FileBadge,'Certificate of Origin'],[FileText,'Bill of Lading'],[ClipboardCheck,'Inspection Report'],[Container,'Container Number'],[Ship,'Shipping Details'],[MapPin,'Consignment Tracking'],[Truck,'Delivery Information']];
function Documents(){return <section className="documents" id="documents"><div className="content"><div className="documents-head"><p className="section-label">Documentation</p><h2>Bill of Lading &amp;<br/>Consignment Tracking.</h2><p>Relevant shipping documents and tracking information are shared with the concerned parties at every stage of the shipment.</p></div><ul className="document-grid">{documents.map(([Icon,label])=><li key={label}><Icon size={26}/><span>{label}</span></li>)}</ul></div></section>}

function Contact(){return <section className="contact" id="contact"><div className="content"><p className="section-label">Vee Nexus Global Resource</p><h2>The next connection<br/>starts here.</h2><a className="contact-email" href={mailto}><span><Mail size={30}/>Email Us: {email}</span><ArrowUpRight/></a><div className="contact-info"><div><h3>S. Gokulakrishnan</h3><p>Proprietor</p><a href="tel:+919884140368"><Phone size={16}/>+91 98841 40368</a><a href="https://wa.me/919884140368" target="_blank" rel="noopener noreferrer">Message on WhatsApp<ArrowUpRight size={16}/></a><SocialLinks className="contact-social"/></div><address>No. 8/1, Bagavantham Street,<br/>T. Nagar, Chennai - 600 017,<br/>Tamil Nadu, India</address><a href="#home" className="back-top">Back to top <ArrowUpRight size={19}/></a></div><div className="footer-word" aria-hidden="true">VEE NEXUS</div><footer><p>© {new Date().getFullYear()} Vee Nexus Global Resource</p><p>Global Sourcing. Verified Quality. Transparent Trade.</p><p>Recycle Today, Better Tomorrow</p></footer></div></section>}
export function App(){const root=useRef<HTMLDivElement>(null);useEffect(()=>{const media=gsap.matchMedia();media.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{gsap.from('.hero-heading h1 span',{yPercent:105,opacity:0,duration:1.05,stagger:.13,ease:'power3.out'});gsap.from('.hero-intro,.hero-bottom',{opacity:0,duration:1,delay:.6});gsap.from('.ship-scene',{opacity:0,yPercent:12,duration:1.4,delay:.15,ease:'power2.out'});gsap.from('.about-photo img',{scale:1.15,ease:'none',scrollTrigger:{trigger:'.about-photo',start:'top bottom',end:'bottom top',scrub:1}});gsap.utils.toArray<HTMLElement>('.process-step').forEach((el,i)=>gsap.from(el,{y:15,duration:.45,delay:i*.06,scrollTrigger:{trigger:'.process-flow',start:'top 85%',once:true}}));},root);return()=>ctx.revert()});return()=>media.revert()},[]);return <div ref={root}><a className="skip-link" href="#about">Skip to content</a><Navigation/><main><Hero/><About/><Credentials/><Gallery/><Services/><Journey/><Products/><Industries/><Sourcing/><Quality/><Process/><Partnership/><Values/><Documents/><Supplier/><Contact/></main><WhatsAppButton/></div>}
if (typeof document !== 'undefined') { const root = document.getElementById('root')!; const app = <React.StrictMode><App/></React.StrictMode>; if (root.hasChildNodes()) hydrateRoot(root, app); else createRoot(root).render(app); }
