import React, { useEffect, useRef, useState } from 'react';
import { createRoot, hydrateRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowRight, ChevronRight, Menu, X, Plus, Minus, Check, Phone } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import ScrollReveal from './components/ScrollReveal';
import ShipScene from './components/ShipScene';
import { nav, grades, pulps, descriptions, pulpDescriptions, photos, gradePhoto, serviceGroups, industries, type Photo } from './data';
import './style.css';
import './sections.css';


gsap.registerPlugin(ScrollTrigger);
const email = 'veenexusglobal@gmail.com';
const whatsapp = 'https://wa.me/919884140368?text=' + encodeURIComponent('Hello Vee Nexus, I would like to discuss recovered paper / pulp.');
const paperPhoto:Photo = {src:'/paper.webp', small:'/paper-small.webp', alt:'Close-up of layered recovered corrugated paper'};
const portPhoto:Photo = {src:'/port.webp', small:'/port-mobile.webp', alt:'Shipping containers in an international port'};
const steps = [
  {name:'Recovered paper', verb:'Source', text:'A new journey starts with recovered material from reliable international suppliers.', photo:photos.occBales},
  {name:'Quality verification', verb:'Verify', text:'Specifications, moisture, outthrows and material evidence are reviewed against the mill’s needs.', photo:photos.occClose},
  {name:'Global sourcing', verb:'Connect', text:'We match available supply with genuine Indian paper-mill requirements.', photo:portPhoto},
  {name:'Ocean freight', verb:'Coordinate', text:'Commercial discussions and shipment coordination connect origin with destination.', photo:photos.containerShip},
  {name:'Indian paper mills', verb:'Transform', text:'Recovered fibre becomes a resource for the next production cycle.', photo:photos.mixed},
  {name:'New paper products', verb:'Renew', text:'Material returns to use through sustainable paper production.', photo:paperPhoto},
];
const origins = [
  {name:'USA', x:225,y:145}, {name:'Canada',x:217,y:90}, {name:'UK',x:493,y:98},
  {name:'Europe',x:535,y:110}, {name:'Central America',x:256,y:209}, {name:'Middle East',x:630,y:173},
  {name:'New Zealand',x:983,y:364},
];
function Picture({photo,sizes='(max-width:640px) 88vw, 48vw'}:{photo:Photo;sizes?:string}){return <img src={photo.src} srcSet={`${photo.small} 800w, ${photo.src} 1400w`} sizes={sizes} alt={photo.alt} loading="lazy"/>}
function Brand(){return <a className="brand" href="#home"><strong>VEE NEXUS</strong><span>GLOBAL RESOURCE</span></a>}
function Action({href,children,outline=false}:{href:string;children:React.ReactNode;outline?:boolean}){return <a className={`action ${outline?'action-outline':''}`} href={href}><span>{children}</span><ArrowUpRight size={18}/></a>}
function Navigation(){
  const [menu,setMenu]=useState(false);const [active,setActive]=useState('home');const [solid,setSolid]=useState(false);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActive(e.target.id)},{rootMargin:'-20% 0px -55% 0px'});nav.forEach(([,id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});const hero=new IntersectionObserver(([e])=>setSolid(!e.isIntersecting),{rootMargin:'-80px 0px 0px 0px'});const el=document.getElementById('hero-top');if(el)hero.observe(el);return()=>{observer.disconnect();hero.disconnect()}},[]);
  useEffect(()=>{if(!menu)return;const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);document.getElementById('menu-toggle')?.focus()}};document.addEventListener('keydown',listener);return()=>document.removeEventListener('keydown',listener)},[menu]);
  return <header className={`site-header ${solid||menu?'is-solid':''}`}><Brand/><nav className={menu?'navigation open':'navigation'} id="mobile-nav" aria-label="Main navigation">{nav.map(([name,id])=><a key={id} href={'#'+id} aria-current={active===id?'location':undefined} onClick={()=>setMenu(false)}>{name}</a>)}</nav><a className="supplier-link" href="#supplier">Become a Supplier<ArrowUpRight size={17}/></a><button id="menu-toggle" className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
}
function Hero(){return <section className="hero" id="home"><div id="hero-top"/><div className="hero-heading"><p className="hero-intro">Recovered paper. Global possibilities.</p><h1><span>Paper</span><span>in motion.</span></h1></div><ShipScene/><div className="hero-bottom"><div><h2>From global sources.<br/>To Indian paper mills.</h2><p>We source recovered paper and pulp products for the next production cycle.</p></div><div className="hero-actions"><Action href="#products">Explore Our Products</Action><a className="simple-link" href="#supplier">Become a Supplier <ArrowUpRight size={16}/></a></div></div><a className="hero-scroll" href="#about" aria-label="Explore the company"><ArrowDown size={21}/></a></section>}
function About(){return <section className="about content" id="about"><div className="about-title"><p className="section-label">Vee Nexus Global Resource</p><h2>Global perspective.<br/>Grounded in Chennai.</h2></div><div className="about-body"><p>We connect international suppliers of recovered paper and pulp with Indian paper mills.</p><p>As a Chennai-based trading and indenting company, we focus on suitable material, genuine mill requirements and commercial terms that work for both sides.</p><div className="about-points"><span>Supplier verification</span><span>Quality-based procurement</span><span>Competitive commercial terms</span><span>Long-term partnerships</span></div></div><div className="about-photo"><img src="/port.webp" srcSet="/port-mobile.webp 800w, /port.webp 1600w" sizes="(max-width:640px) 88vw, 48vw" alt="Aerial view of containers arranged at a shipping port" loading="lazy"/><p>International supply. Indian market knowledge.</p></div><div className="about-statement">Recycle today.<br/>Better tomorrow.</div></section>}
function Gallery(){const items=[{photo:photos.occBales,label:'OCC bales',wide:true},{photo:photos.mixed,label:'Mixed paper'},{photo:photos.onp,label:'ONP / OINP'},{photo:photos.crane,label:'Container loading'},{photo:photos.shipSea,label:'Ocean freight',wide:true}];
 return <section className="gallery" aria-label="Material and shipping photographs"><div className="gallery-track" tabIndex={0} role="group" aria-label="Photographs, scroll sideways on small screens">{items.map(item=><figure key={item.label} className={item.wide?'wide':''}><Picture photo={item.photo} sizes="(max-width:640px) 80vw, 40vw"/><figcaption>{item.label}</figcaption></figure>)}</div><p className="gallery-note content">Recovered paper, from the baling yard to the ship’s hold. Photographs illustrate material categories.</p></section>}
function Services(){const [group,setGroup]=useState(0);const current=serviceGroups[group];
 return <section className="services content" id="services"><div className="services-title"><p className="section-label">What we do</p><h2>End to end.<br/>Yard to mill.</h2><p>Sourcing, quality, documentation, shipping and marine services under one point of contact.</p></div><div className="services-tabs" role="tablist" aria-label="Service areas">{serviceGroups.map((g,i)=><button key={g.id} role="tab" id={'service-tab-'+g.id} aria-selected={group===i} aria-controls="service-panel" tabIndex={group===i?0:-1} onClick={()=>setGroup(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowDown'||e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();const next=(i+(e.key==='ArrowRight'||e.key==='ArrowDown'?1:serviceGroups.length-1))%serviceGroups.length;setGroup(next);document.getElementById('service-tab-'+serviceGroups[next].id)?.focus()}}}><span>0{i+1}</span>{g.label}</button>)}</div><div className="services-panel" id="service-panel" role="tabpanel" aria-labelledby={'service-tab-'+current.id} key={current.id}><div className="services-photo"><Picture photo={current.photo}/><p>{current.intro}</p></div><ol className="service-list">{current.items.map(([name,text])=><li key={name}><h3>{name}</h3><p>{text}</p></li>)}</ol></div><div className="services-cta"><p>Need one service or the full chain?</p><Action href={`mailto:${email}?subject=${encodeURIComponent('Service enquiry: '+current.label)}`}>Enquire about {current.label.toLowerCase()}</Action></div></section>}
function Industries(){return <section className="industries content" aria-labelledby="industries-title"><p className="section-label">Who we serve</p><h2 id="industries-title">Every mill needs<br/>a different fibre.</h2><div className="industry-grid">{industries.map((ind,i)=><article key={ind.name}><span>0{i+1}</span><h3>{ind.name}</h3><p>{ind.text}</p><ul aria-label={'Typical grades for '+ind.name}>{ind.grades.map(g=><li key={g}>{g}</li>)}</ul></article>)}</div></section>}
function WhatsAppButton(){return <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Chat with Vee Nexus on WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M17.47 14.38c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.16-.17.2-.35.22-.64.08-.3-.15-1.26-.46-2.39-1.48-.88-.79-1.48-1.76-1.65-2.06-.17-.3-.02-.46.13-.6.13-.14.3-.35.45-.52.15-.18.2-.3.3-.5.1-.2.05-.37-.03-.52-.07-.15-.67-1.61-.91-2.2-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.48 0 1.46 1.07 2.88 1.21 3.07.15.2 2.1 3.2 5.08 4.49.71.3 1.26.49 1.7.63.71.22 1.36.19 1.87.12.57-.09 1.76-.72 2-1.41.25-.7.25-1.29.18-1.41-.08-.13-.28-.2-.57-.35m-5.42 7.4h-.01a9.87 9.87 0 0 1-5.03-1.38l-.36-.21-3.74.98 1-3.65-.24-.37a9.86 9.86 0 0 1-1.51-5.26c0-5.45 4.44-9.88 9.89-9.88 2.64 0 5.12 1.03 6.99 2.9a9.83 9.83 0 0 1 2.89 6.99c0 5.45-4.44 9.88-9.88 9.88m8.41-18.3A11.82 11.82 0 0 0 12.05 0C5.5 0 .16 5.34.16 11.89c0 2.1.55 4.14 1.59 5.95L.06 24l6.3-1.65a11.88 11.88 0 0 0 5.68 1.45h.01c6.55 0 11.89-5.34 11.89-11.9a11.82 11.82 0 0 0-3.48-8.4Z"/></svg><span className="whatsapp-label">Chat on WhatsApp</span></a>}
function Journey(){const [stage,setStage]=useState(0);const section=useRef<HTMLElement>(null);
  useEffect(()=>{const media=gsap.matchMedia();media.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{const trigger=ScrollTrigger.create({trigger:section.current,start:'top top',end:'bottom bottom',onUpdate:s=>setStage(Math.min(5,Math.floor(s.progress*6)))});return()=>trigger.kill()});return()=>media.revert()},[]);
  return <section className="journey" ref={section} id="journey"><div className="journey-sticky"><div className="journey-copy"><p className="section-label">The material journey</p><h2>Waste is only<br/>the beginning.</h2><div className="journey-description" key={stage}><span className="stage-number">0{stage+1}</span><div><h3>{steps[stage].name}</h3><p>{steps[stage].text}</p></div></div></div><div className={'journey-art stage-'+stage}><Picture key={steps[stage].photo.src} photo={steps[stage].photo}/><span className="journey-verb" aria-hidden="true">{steps[stage].verb}</span><div className="paper-window"/></div><div className="journey-controls" aria-label="Explore the material journey">{steps.map((step,i)=><button key={step.name} className={stage===i?'active':''} onClick={()=>setStage(i)} aria-pressed={stage===i}><span>0{i+1}</span>{step.name}<ChevronRight size={16}/></button>)}</div></div></section>}
function Products(){const [category,setCategory]=useState<'paper'|'pulp'>('paper');const [selected,setSelected]=useState('OCC 11');const list=category==='paper'?grades:pulps;
 return <section className="products content" id="products"><div className="products-title"><p className="section-label">What we source</p><h2>Good material.<br/>The right match.</h2><p>Recovered paper and pulp, sourced to fit Indian mill requirements.</p></div><div className="category-control" role="group" aria-label="Product category">{(['paper','pulp'] as const).map(c=><button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setSelected(c==='paper'?'OCC 11':'NBSK')}}>{c==='paper'?'Recovered paper':'Pulp products'}<span>{String((c==='paper'?grades:pulps).length).padStart(2,'0')}</span></button>)}</div><div className="materials"><div className={`material-photo ${category}`}><Picture key={category==='paper'?gradePhoto(selected).src:'pulp'} photo={category==='paper'?gradePhoto(selected):paperPhoto}/><span className="material-type" aria-hidden="true">{category==='paper'?'Recovered.':'Renewed.'}</span></div><div className="material-browser"><div className="grade-buttons" role="group" aria-label="Select a product grade">{list.map(grade=><button key={grade} className={selected===grade?'selected':''} aria-pressed={selected===grade} onClick={()=>setSelected(grade)}>{grade}{selected===grade?<ArrowUpRight size={18}/>:<Plus size={17}/>}</button>)}</div><div className="material-detail" aria-live="polite" key={selected}><p>Selected material</p><h3>{selected}</h3><p>{descriptions[selected]||pulpDescriptions[selected]+'. Availability and suitability subject to mill requirements.'}</p><a className="simple-link" href={`mailto:${email}?subject=${encodeURIComponent('Product enquiry: '+selected)}`}>Enquire about {selected}<ArrowUpRight size={17}/></a></div></div></div><p className="materials-note">We are open to suitable grades based on Indian paper-mill requirements.</p></section>
}
function Sourcing(){const [origin,setOrigin]=useState(0);const map=useRef<SVGSVGElement>(null);
 useEffect(()=>{const media=gsap.matchMedia();media.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{gsap.fromTo('.selected-route',{strokeDashoffset:1},{strokeDashoffset:0,duration:1.5,ease:'power2.inOut',scrollTrigger:{trigger:map.current,start:'top 85%',once:true}})},map);return()=>ctx.revert()});return()=>media.revert()},[origin]);
 const selected=origins[origin];
 return <section className="sourcing" id="sourcing"><div className="content sourcing-content"><div className="sourcing-title"><p className="section-label">Global sourcing</p><h2>Many origins.<br/>One connection.</h2><p>Building reliable supplier relationships across international recovered-paper markets.</p></div><div className="origins" role="group" aria-label="Explore sourcing regions">{origins.map((o,i)=><button key={o.name} onClick={()=>setOrigin(i)} aria-pressed={origin===i}>{o.name}</button>)}</div><div className="map-wrap"><img src="/world.svg" alt="World map" loading="lazy"/><svg ref={map} viewBox="0 0 1000 500" role="img" aria-label={`Illustrative sourcing route from ${selected.name} to Chennai, India`}><g className="map-routes">{origins.map(o=><path key={o.name} d={`M${o.x},${o.y} Q${(o.x+722)/2},${Math.min(o.y,214)-110} 722,214`}/>)}</g><path className="selected-route" key={origin} pathLength="1" d={`M${selected.x},${selected.y} Q${(selected.x+722)/2},${Math.min(selected.y,214)-110} 722,214`}/><circle className="origin-node" cx={selected.x} cy={selected.y} r="5"/><circle className="destination-ring" cx="722" cy="214" r="13"/><circle className="destination-node" cx="722" cy="214" r="5"/><text x="743" y="217">Chennai, India</text><text x={selected.x} y={selected.y+25} textAnchor={selected.x>900?'end':'middle'}>{selected.name}</text></svg></div><div className="sourcing-footer"><p>Quality. Availability. Pricing.<br/>Freight economics. Specifications. Reliability.</p><div><p>We welcome suppliers with consistent quality and regular monthly quantities.</p><small>Open to other suitable origins.</small></div></div></div></section>
}
function Quality(){return <section className="quality content" id="quality"><div><p className="section-label">Procurement with care</p><h2>Quality before<br/>quantity.</h2><p>Every opportunity is evaluated around specifications, moisture, outthrows, contamination, photographic evidence and available inspection information.</p><a className="simple-link" href="#supplier">What to share with us<ArrowRight size={18}/></a></div><div className="quality-groups"><article><span className="quality-symbol"><Check size={24}/></span><h3>Know the material.</h3><p>Grade specifications, moisture, outthrows and contamination details.</p></article><article><span className="quality-symbol"><Check size={24}/></span><h3>See the evidence.</h3><p>Bale condition, photographs, material videos and available inspection reports.</p></article><article><span className="quality-symbol"><Check size={24}/></span><h3>Understand the supply.</h3><p>Regular supply capacity, origin, loading quantities and shipment readiness.</p></article></div></section>}
const processSteps=[['Mill requirement','Grade, quantity, specification and target price from the mill.'],['Supplier discovery','Matching verified suppliers and origins to the requirement.'],['Specification & quality review','Moisture, outthrows, prohibitives, photographs and videos checked.'],['Commercial negotiation','Price, FOB / CFR / CIF terms, payment and shipment period agreed.'],['Contract & documentation','Contract issued; invoice, packing list and certificates prepared.'],['Inspection & loading','Pre-shipment inspection, loading supervision and container photographs.'],['Ocean freight & tracking','Booking, bill of lading, vessel tracking and ETA updates.'],['Arrival & feedback','Port clearance coordination, delivery to the mill and quality feedback.']];
function Process(){return <section className="process content" id="process"><p className="section-label">How we work</p><h2>A clear path<br/>from supplier to mill.</h2><div className="process-flow">{processSteps.map(([name,text],i)=><div className="process-step" key={name}><span>0{i+1}</span><h3>{name}</h3><p>{text}</p>{i<processSteps.length-1&&<ArrowRight size={20}/>}</div>)}</div><p className="commercial-terms">Commercial discussions may include <strong>FOB</strong><strong>CFR</strong><strong>CIF Chennai</strong></p></section>}
function Partnership(){return <section className="partnership" id="partnership"><div className="content"><p className="section-label">The long view</p><h2>Not one shipment.<br/>A lasting partnership.</h2><ScrollReveal text="Quality. Reliability. Transparency. Competitive pricing. Long-term partnership."/><div className="partnership-close"><p>These are the foundations of the supplier relationships we want to build.</p><a href="#supplier" className="round-link" aria-label="Become a supplier"><ArrowUpRight size={30}/></a></div></div></section>}
const supplierGroups=[{title:'Company',items:['Company information','Monthly supply capacity','Loading port']},{title:'Product',items:['Product grade & origin','Quality specification','Moisture %, outthrows % and contamination details','Bale weight & dimensions',"40′ HC loading quantity"]},{title:'Commercial',items:['MOQ','Shipment lead time','FOB / CFR / CIF pricing','Payment terms']},{title:'Quality evidence',items:['Bale photographs','Loading photographs','Material videos','Inspection reports, if available']}];
function Supplier(){const [open,setOpen]=useState<number[]>([0]);const toggle=(i:number)=>setOpen(a=>a.includes(i)?a.filter(x=>x!==i):[...a,i]);return <section className="supplier content" id="supplier"><div className="supplier-heading"><p className="section-label">Become a Supplier</p><h2>Supply recovered paper?<br/>Let's talk.</h2><p>We welcome reliable international suppliers who can provide consistent quality and regular quantities.</p><Action href={`mailto:${email}?subject=Supplier%20introduction&body=Company%20name%3A%0AProduct%20grade%20and%20origin%3A%0AQuality%20specifications%3A%0AMonthly%20capacity%3A%0ALoading%20port%3A%0APricing%20and%20payment%20terms%3A%0A%0APlease%20attach%20material%20photographs%20and%20available%20inspection%20reports.`}>Send Supplier Details</Action></div><div className="supplier-checklist"><p>For a useful first conversation, please share:</p>{supplierGroups.map((group,i)=><div className="supplier-group" key={group.title}><button aria-expanded={open.includes(i)} aria-controls={'supplier-panel-'+i} onClick={()=>toggle(i)}>{group.title}{open.includes(i)?<Minus size={19}/>:<Plus size={19}/>}</button><div id={'supplier-panel-'+i} hidden={!open.includes(i)}><ul>{group.items.map(item=><li key={item}>{item}</li>)}</ul></div></div>)}</div></section>}
function Contact(){return <><div className="trust-statement content"><p>Global sourcing</p><p>Quality assurance</p><p>Trusted partnership</p><p>Sustainable future</p></div><section className="contact" id="contact"><div className="content"><p className="section-label">Vee Nexus Global Resource</p><h2>The next connection<br/>starts here.</h2><a className="contact-email" href={'mailto:'+email}>{email}<ArrowUpRight/></a><div className="contact-info"><div><h3>S. Gokulakrishnan</h3><p>Proprietor</p><a href="tel:+919884140368"><Phone size={16}/>+91 98841 40368</a><a href="https://wa.me/919884140368" target="_blank" rel="noopener noreferrer">Message on WhatsApp<ArrowUpRight size={16}/></a></div><address>No. 8/1, Bagavantham Street,<br/>T. Nagar, Chennai - 600 017,<br/>Tamil Nadu, India</address><a href="#home" className="back-top">Back to top <ArrowUpRight size={19}/></a></div><div className="footer-word" aria-hidden="true">VEE NEXUS</div><footer><p>© {new Date().getFullYear()} Vee Nexus Global Resource</p><p>Importers & Indenters of Waste Paper for Paper Mills</p><p>Recycle Today, Better Tomorrow</p></footer></div></section></>}
export function App(){const root=useRef<HTMLDivElement>(null);useEffect(()=>{const media=gsap.matchMedia();media.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{gsap.from('.hero-heading h1 span',{yPercent:105,opacity:0,duration:1.05,stagger:.13,ease:'power3.out'});gsap.from('.hero-intro,.hero-bottom',{opacity:0,duration:1,delay:.6});gsap.from('.ship-scene',{opacity:0,yPercent:12,duration:1.4,delay:.15,ease:'power2.out'});gsap.from('.about-photo img',{scale:1.15,ease:'none',scrollTrigger:{trigger:'.about-photo',start:'top bottom',end:'bottom top',scrub:1}});gsap.utils.toArray<HTMLElement>('.process-step').forEach((el,i)=>gsap.from(el,{y:15,duration:.45,delay:i*.06,scrollTrigger:{trigger:'.process-flow',start:'top 85%',once:true}}));},root);return()=>ctx.revert()});return()=>media.revert()},[]);return <div ref={root}><a className="skip-link" href="#about">Skip to content</a><Navigation/><main><Hero/><About/><Gallery/><Services/><Journey/><Products/><Industries/><Sourcing/><Quality/><Process/><Partnership/><Supplier/><Contact/></main><WhatsAppButton/></div>}
if (typeof document !== 'undefined') { const root = document.getElementById('root')!; const app = <React.StrictMode><App/></React.StrictMode>; if (root.hasChildNodes()) hydrateRoot(root, app); else createRoot(root).render(app); }



